var korean = new Array(
    "미국 사람",
    "종로",
    "배우다",
    "외국 사람",
    "교실",
    "중국 사람",
    "일본 사람",
    "독일 사람",
    "주말에",
    "수업",
    "국장",
    "영화",
    "저녁",
    "맥주",
    "그리고",
    "명동",
    "요즘",
    "오전",
    "오후",
    "숙제",
    "토요일",
    "시장",
    "옷",
    "구두",
    "과일",
    "사람",
    "아주",
    "재미있다",
    "가족",
    "고향",
    "계시다",
    "뉴욕",
    "남동생",
    "열아홉",
    "한달",
    "여행",
    "가르지다",
    "같이",
    "멀다",
    "저녁 식사",
    "불고기",
    "좋아하다",
    "한식집",
    "근처",
    "별로",
    "천천히",
    "걸어서 가다",
    "시청",
    "끝나다",
    "조금",
    "주말마다",
    "동산",
    "지난",
    "주",
    "북한산",
    "시내",
    "기깝다",
    "앞",
    "피곤하다",
    "한남동",
    "살다",
    "지난해",
    "하숙집",
    "방",
    "빌리다",
    "식사",
    "준비",
    "빨래",
    "온돌방",
    "크다",
    "따뜻하다",
    "기타",
    "치다",
    "노래를 부르다",
    "어렵다",
    "지하철",
    "타다",
    "버스",
    "걸리다",
    "깨끗하다",
    "빈 자리",
    "앉다",
    "보통",
    "구경하다",
    "아주머니",
    "아저씨",
    "이번",
    "설악산",
    "기차",
    "비행기",
    "바다",
    "아름답다",
    "요금",
    "동해",
    "전에",
    "처음에",
    "모르다",
    "생활",
    "소개하다",
    "기쁘다",
    "지금",
    "아직",
    "혼자",
    "동대문",
    "다음",


var english = new Array(
    "American (person)",
    "Jong-no (district)",
    "to learn",
    "foreigner",
    "classroom",
    "Chinese (person)",
    "Japanese (person)",
    "German (person)",
    "on the weekend",
    "class, lesson",
    "theater",
    "movie",
    "dinner, evening",
    "beer",
    "and (at beginning of sentence)",
    "Myeong-dong (district)",
    "these days",
    "morning, A.M.",
    "afternoon, P.M.",
    "homework",
    "Saturday",
    "market",
    "clothes, dress",
    "shoes",
    "fruit",
    "people, person",
    "very",
    "to be interesting",
    "family",
    "hometown",
    "to exist [honorific]",
    "New York",
    "younger brother",
    "nineteen",
    "one month",
    "trip",
    "to teach",
    "together",
    "to be far",
    "dinner (meal)",
    "Bulgogi",
    "to like",
    "Korean restaurant",
    "near",
    "particularly",
    "slowly",
    "to go on foot",
    "City Hall",
    "to be finished",
    "a little",
    "every weekend",
    "hiking, climbing",
    "last, past",
    "week",
    "Mt. Pukhan",
    "downtown",
    "to be near",
    "front",
    "to be tired",
    "Hannam-dong (district)",
    "to live",
    "last year",
    "boarding house",
    "room",
    "to rent",
    "meal",
    "preparation",
    "a wash",
    "Ondol-pang (heating system)",
    "to be big, to be large",
    "to be warm",
    "guitar",
    "to play (guitar, piano, etc.)",
    "to sing a song",
    "to be difficult",
    "subway",
    "to ride",
    "bus",
    "to take (time)",
    "to be clean",
    "unoccupied seat",
    "to sit down",
    "usually",
    "to see a sight",
    "married woman",
    "married man",
    "this time",
    "Mt. Solak",
    "train",
    "airplane",
    "sea, ocean",
    "to be beautiful",
    "fare",
    "Tonghae (sea)",
    "before, ago",
    "at first",
    "to not know",
    "life, living",
    "to introduce",
    "to be happy",
    "now",
    "(not) yet",
    "alone, by oneself",
    "East Gate",
    "next");
